#!/bin/bash
#
# Grabs the latest version of Formbuilder from the Bower registry,
# and installs it on the gh-pages branch.
#

echo 'Deploying docs...'

git checkout gh-pages
bower update formbuilder
rm -rf bower_components/font-awesome/src/
git add .
git commit -am 'Deploying docs'
git push origin gh-pages

# Cleanup
git checkout master
bower install
