#!/bin/bash

echo 'Deploying docs...'

git checkout gh-pages-2
bower install
rm -rf bower_components/font-awesome/src
git add .
git commit -am 'Deploying docs'
git push origin gh-pages-2

git checkout master
bower install
