#!/bin/bash

echo 'Deploying docs...'

git checkout gh-pages
bower update formbuilder
rm -rf bower_components/font-awesome/src/
git add .
git commit -am 'Deploying docs'
git push origin gh-pages

# Cleanup
git checkout master
bower install
